"""Mode-resolved overlap regularization for noisy generalized eigenproblems."""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np
from scipy.linalg import eigh

from .krylov import KrylovEigenResult, KrylovErrorModel


@dataclass(frozen=True)
class OverlapModeAssessment:
    eigenvalues: np.ndarray
    deterministic_bias: np.ndarray
    standard_deviation: np.ndarray
    thresholds: np.ndarray
    keep: np.ndarray


def assess_overlap_modes(
    overlap: np.ndarray,
    error_model: KrylovErrorModel,
    *,
    safety_factor: float = 1.0,
    absolute_floor: float = 1e-12,
    include_predicted_bias: bool = False,
) -> OverlapModeAssessment:
    """Assess each measured overlap eigenmode against its own predicted error.

    For an overlap eigenvector ``v_k``, the first-order eigenvalue perturbation
    generated by scalar estimator ``x_i`` is

    ``g_ki = v_k^dagger (dS/dx_i) v_k``.

    The stochastic uncertainty is therefore ``sqrt(g Sigma g^T)`` rather than
    a global Frobenius norm of the whole overlap perturbation. This is typically
    less conservative than one scalar cutoff while remaining directly tied to
    the propagated estimator covariance.
    """

    matrix = np.asarray(overlap, dtype=complex)
    if matrix.ndim != 2 or matrix.shape[0] != matrix.shape[1]:
        raise ValueError("overlap must be square")
    if not np.allclose(matrix, matrix.conj().T, atol=1e-9, rtol=0.0):
        raise ValueError("overlap must be Hermitian")
    if safety_factor < 0 or absolute_floor < 0:
        raise ValueError("safety_factor and absolute_floor must be nonnegative")
    if error_model.bias_s.shape != matrix.shape:
        raise ValueError("error model and overlap dimensions do not agree")

    values, vectors = eigh(matrix)
    deterministic = np.zeros(len(values), dtype=float)
    std = np.zeros(len(values), dtype=float)

    if include_predicted_bias:
        for index in range(len(values)):
            vector = vectors[:, index]
            deterministic[index] = abs(
                float(np.real(vector.conj().T @ error_model.bias_s @ vector))
            )

    if error_model.observable_covariance is not None:
        sigma = np.asarray(error_model.observable_covariance, dtype=float)
        for index in range(len(values)):
            vector = vectors[:, index]
            gradients = np.array(
                [
                    float(np.real(vector.conj().T @ weight @ vector))
                    for weight in error_model.observable_weights_s
                ],
                dtype=float,
            )
            variance = float(gradients @ sigma @ gradients)
            std[index] = np.sqrt(max(variance, 0.0))
    elif error_model.mode_covariance is not None:
        sigma = np.asarray(error_model.mode_covariance, dtype=float)
        for index in range(len(values)):
            vector = vectors[:, index]
            gradients = np.array(
                [
                    float(np.real(vector.conj().T @ derivative @ vector))
                    for derivative in error_model.jacobian_s
                ],
                dtype=float,
            )
            variance = float(gradients @ sigma @ gradients)
            std[index] = np.sqrt(max(variance, 0.0))

    thresholds = absolute_floor + safety_factor * (deterministic + std)
    keep = values > thresholds
    return OverlapModeAssessment(
        eigenvalues=values,
        deterministic_bias=deterministic,
        standard_deviation=std,
        thresholds=thresholds,
        keep=keep,
    )


def solve_noise_aware_krylov(
    hamiltonian: np.ndarray,
    overlap: np.ndarray,
    error_model: KrylovErrorModel,
    *,
    root: int = 0,
    safety_factor: float = 1.0,
    absolute_floor: float = 1e-12,
    include_predicted_bias: bool = False,
) -> tuple[KrylovEigenResult, OverlapModeAssessment]:
    """Solve Hc=ESc after retaining overlap modes above their own error scale."""

    h = np.asarray(hamiltonian, dtype=complex)
    s = np.asarray(overlap, dtype=complex)
    if h.ndim != 2 or h.shape[0] != h.shape[1] or s.shape != h.shape:
        raise ValueError("H and S must be square matrices of the same shape")
    if not np.allclose(h, h.conj().T, atol=1e-9, rtol=0.0):
        raise ValueError("H must be Hermitian")

    assessment = assess_overlap_modes(
        s,
        error_model,
        safety_factor=safety_factor,
        absolute_floor=absolute_floor,
        include_predicted_bias=include_predicted_bias,
    )
    overlap_values, overlap_vectors = eigh(s)
    keep = assessment.keep
    rank = int(np.count_nonzero(keep))
    if rank == 0:
        raise ValueError("no overlap eigenmode exceeds its predicted error scale")
    if root < 0 or root >= rank:
        raise ValueError("root is outside the retained Krylov rank")

    whitening = overlap_vectors[:, keep] / np.sqrt(overlap_values[keep])[None, :]
    reduced_h = whitening.conj().T @ h @ whitening
    energies, vectors = eigh(reduced_h)
    vector = whitening @ vectors[:, root]
    norm = float(np.real(vector.conj().T @ s @ vector))
    if norm <= 0:
        raise ValueError("retained generalized eigenvector has nonpositive S norm")
    vector = vector / np.sqrt(norm)
    result = KrylovEigenResult(
        energy=float(np.real(energies[root])),
        vector=vector,
        retained_overlap_rank=rank,
        overlap_floor=float(np.max(assessment.thresholds[keep], initial=absolute_floor)),
        overlap_eigenvalues=overlap_values,
    )
    return result, assessment
